module dealloc_part_mod
!
!  module declarations
!
use global_pointers  ! global data pointers
!
!  data definition module(s)
!
use precision        ! single and double precision
      use timers

use dealloc_mod      ! generic module for memory de-allocation, including error handling
!
implicit none        ! force explicit typing
!
contains
      subroutine dealloc_part()
      integer(4) ithndl              ! handle to time this subroutine
      data       ithndl / 0 /
      if ( timon ) call timstrt( "dealloc_part", ithndl )
!
!                        d e l p a r    v3.60
!
!     created               : july 2008, by antoon koster
!
!     function              : free dynamic memory for global pointers
!
      call dealloc(abuoy      )
      call dealloc(acf        )
      call dealloc(aconc      )
      call dealloc(aconud     )
      call dealloc(adepth     )
      call dealloc(amap       )
      call dealloc(amapsett   )
      call dealloc(amassc     )
      call dealloc(amassd     )
      call dealloc(angle      )
      call dealloc(apeak      )
      call dealloc(area       )
      call dealloc(atotal     )
      call dealloc(atrack     )
      call dealloc(cbuff      )
      call dealloc(cdelv      )
      call dealloc(chismp     )
      call dealloc(chispl     )
      call dealloc(conc       )
      call dealloc(const      )
      call dealloc(constev    )
      call dealloc(c2         )
      call dealloc(decay      )
      call dealloc(decays     )
      call dealloc(depth      )
      call dealloc(dfact      )
      call dealloc(dps        )
      call dealloc(drand      )
      call dealloc(dx         )
      call dealloc(dy         )
      call dealloc(elt_names  )
      call dealloc(elt_types  )
      call dealloc(elt_dims   )
      call dealloc(elt_bytes  )
      call dealloc(finud      )
      call dealloc(floil      )
      call dealloc(flow       )
      call dealloc(flres      )
      call dealloc(fractd     )
      call dealloc(fracte     )
      call dealloc(fstick     )
      call dealloc(ftime      )
      call dealloc(fwatoil    )
      call dealloc(ibuff      )
      call dealloc(ictime     )
      call dealloc(ictmax     )
      call dealloc(idtime     )
      call dealloc(ifopt      )
      call dealloc(iftime     )
      call dealloc(ihplot     )
      call dealloc(imap       )
      call dealloc(imask      )
      call dealloc(ioptrad    )
      call dealloc(ipnt       )
      call dealloc(ipset      )
      call dealloc(iptime     )
      call dealloc(isfile     )
      call dealloc(isfud      )
      call dealloc(isub       )
      call dealloc(iutime     )
      call dealloc(ivtime     )
      call dealloc(iwndtm     )
      call dealloc(iwtime     )
      call dealloc(kpart      )
      call dealloc(kwaste     )
      call dealloc(lgrid      )
      call dealloc(lgrid2     )
      call dealloc(linear     )
      call dealloc(locdep     )
      call dealloc(mapsub     )
      call dealloc(mcell      )
      call dealloc(mpart0     )
      call dealloc(mpart      )
      call dealloc(mplsta     )
      call dealloc(mstat      )
      call dealloc(mstick     )
      call dealloc(mwaste     )
      call dealloc(nbin       )
      call dealloc(ncell      )
      call dealloc(ncheck     )
      call dealloc(ndprt      )
      call dealloc(nmconr     )
      call dealloc(nmdyer     )
      call dealloc(nmstat     )
      call dealloc(nosud      )
      call dealloc(nosys      )
      call dealloc(npart0     )
      call dealloc(npart      )
      call dealloc(nplay      )
      call dealloc(nplot      )
      call dealloc(nplsta     )
      call dealloc(nstat      )
      call dealloc(nwaste     )
      call dealloc(radius     )
      call dealloc(rbuff      )
      call dealloc(rbuffr     )
      call dealloc(recovr     )
      call dealloc(rem        )
      call dealloc(rhooilv    )
      call dealloc(stoch      )
      call dealloc(stoil      )
      call dealloc(subst      )
      call dealloc(substi     )
      call dealloc(subst2     )
      call dealloc(subsud     )
      call dealloc(t0buoy     )
      call dealloc(t0cf       )
      call dealloc(tcktot     )
      call dealloc(title      )
      call dealloc(tmass      )
      call dealloc(tmassc     )
      call dealloc(tmassu     )
      call dealloc(tmasud     )
      call dealloc(totfe      )
      call dealloc(track      )
      call dealloc(qentr      )
      call dealloc(uscal      )
      call dealloc(vdiff      )
      call dealloc(velo       )
      call dealloc(viso       )
      call dealloc(visowat    )
      call dealloc(volfracw   )
      call dealloc(vol1       )
      call dealloc(vol2       )
      call dealloc(volume     )
      call dealloc(vrtdsp     )
      call dealloc(vsfact     )
      call dealloc(vsfour     )
      call dealloc(wdira      )
      call dealloc(wevap      )
      call dealloc(window     )
      call dealloc(wparm      )
      call dealloc(wpart      )
      call dealloc(wsettl     )
      call dealloc(wveloa     )
      call dealloc(xa0        )
      call dealloc(xa         )
      call dealloc(xb         )
      call dealloc(xpart0     )
      call dealloc(xpart      )
      call dealloc(xpol       )
      call dealloc(xstat      )
      call dealloc(xwaste     )
      call dealloc(xyztrk     )
      call dealloc(ya0        )
      call dealloc(ya         )
      call dealloc(yb         )
      call dealloc(ypart0     )
      call dealloc(ypart      )
      call dealloc(ypol       )
      call dealloc(ystat      )
      call dealloc(ywaste     )
      call dealloc(za         )
      call dealloc(zlevel     )
      call dealloc(zpart      )
      call dealloc(zwaste     )
      if ( timon ) call timstop ( ithndl )
      return
      end subroutine dealloc_part
end module dealloc_part_mod
