!!  Copyright(C) Stichting Deltares, 2012.
!!
!!  This program is free software: you can redistribute it and/or modify
!!  it under the terms of the GNU General Public License version 3,
!!  as published by the Free Software Foundation.
!!
!!  This program is distributed in the hope that it will be useful,
!!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
!!  GNU General Public License for more details.
!!
!!  You should have received a copy of the GNU General Public License
!!  along with this program. If not, see <http://www.gnu.org/licenses/>.
!!
!!  contact: delft3d.support@deltares.nl
!!  Stichting Deltares
!!  P.O. Box 177
!!  2600 MH Delft, The Netherlands
!!
!!  All indications and logos of, and references to registered trademarks
!!  of Stichting Deltares remain the property of Stichting Deltares. All
!!  rights reserved.

C     FILL THE OUTPUT ARRAY
      WRITE(IDEBUG,*) 'FOP1        = ',FOP1
      WRITE(IDEBUG,*) 'FOP3        = ',FOP3
      WRITE(IDEBUG,*) 'FOP4        = ',FOP4
      WRITE(IDEBUG,*) 'FPP1        = ',FPP1
      WRITE(IDEBUG,*) 'FPP3        = ',FPP3
      WRITE(IDEBUG,*) 'FPP4        = ',FPP4
      WRITE(IDEBUG,*) 'FMP1        = ',FMP1
      WRITE(IDEBUG,*) 'FMP3        = ',FMP3
      WRITE(IDEBUG,*) 'FMP4        = ',FMP4
      WRITE(IDEBUG,*) 'DTA         = ',DTA
      WRITE(IDEBUG,*) 'BTHICK(1)   = ',BTHICK(1)
      WRITE(IDEBUG,*) 'BTHICK(2)   = ',BTHICK(2)
      WRITE(IDEBUG,*) 'BTHICK(3)   = ',BTHICK(3)
      WRITE(IDEBUG,*) 'BTHICK(4)   = ',BTHICK(4)
      WRITE(IDEBUG,*) 'CA1         = ',CA1
      WRITE(IDEBUG,*) 'CA2         = ',CA2
      WRITE(IDEBUG,*) 'CA4         = ',CA4
      WRITE(IDEBUG,*) 'CDET1       = ',CDET1
      WRITE(IDEBUG,*) 'CDET4       = ',CDET4
      WRITE(IDEBUG,*) 'CREF1       = ',CREF1
      WRITE(IDEBUG,*) 'CDTN1       = ',CDTN1
      WRITE(IDEBUG,*) 'CDTN4       = ',CDTN4
      WRITE(IDEBUG,*) 'CRFN1       = ',CRFN1
      WRITE(IDEBUG,*) 'CDTP1       = ',CDTP1
      WRITE(IDEBUG,*) 'CDTP4       = ',CDTP4
      WRITE(IDEBUG,*) 'CRFP1       = ',CRFP1
      WRITE(IDEBUG,*) 'CN1         = ',CN1
      WRITE(IDEBUG,*) 'CP1         = ',CP1
      WRITE(IDEBUG,*) 'CP3         = ',CP3
      WRITE(IDEBUG,*) 'CP4         = ',CP4
      WRITE(IDEBUG,*) 'CPP1        = ',CPP1
      WRITE(IDEBUG,*) 'CPP3        = ',CPP3
      WRITE(IDEBUG,*) 'CPP4        = ',CPP4
      WRITE(IDEBUG,*) 'CMP1        = ',CMP1
      WRITE(IDEBUG,*) 'CMP3        = ',CMP3
      WRITE(IDEBUG,*) 'CMP4        = ',CMP4
      WRITE(IDEBUG,*) 'CS1         = ',CS1
