#!/bin/ksh
#
# diorun: run processes that are coupled on line by DelftIO SharedMem
#
# Stef.Hummel@deltares.nl
#
# (c) Deltares, Mar 2002
#

pageSize=16384

progName=`basename $0`

if [ $# -ne 2 -a  $# -ne 3 ] ; then
    echo "Usage: $progName proc1 proc2 [ sleepTime ] ]"
    echo "\tRemark: Currently only 2 processes are allowed"
    exit 1
fi

esmContext=`create.$ARCH $pageSize 2>&1 | grep Context | awk '{ print $4}'`

echo "Starting processes for shared mem context: $esmContext"

echo DIO_SHM_ESM=$esmContext

exit

$1 &
if [ $# = 3 ] ; then
    sleep $3
fi
$2

if [ "$esmContext" != -1 -a "$esmContext" != "" ] ; then
    delete.$ARCH $esmContext
fi
