!----- LGPL --------------------------------------------------------------------
!                                                                               
!  Copyright (C)  Stichting Deltares, 2011-2012.                                
!                                                                               
!  This library is free software; you can redistribute it and/or                
!  modify it under the terms of the GNU Lesser General Public                   
!  License as published by the Free Software Foundation version 2.1.                 
!                                                                               
!  This library is distributed in the hope that it will be useful,              
!  but WITHOUT ANY WARRANTY; without even the implied warranty of               
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU            
!  Lesser General Public License for more details.                              
!                                                                               
!  You should have received a copy of the GNU Lesser General Public             
!  License along with this library; if not, see <http://www.gnu.org/licenses/>. 
!                                                                               
!  contact: delft3d.support@deltares.nl                                         
!  Stichting Deltares                                                           
!  P.O. Box 177                                                                 
!  2600 MH Delft, The Netherlands                                               
!                                                                               
!  All indications and logos of, and references to, "Delft3D" and "Deltares"    
!  are registered trademarks of Stichting Deltares, and remain the property of  
!  Stichting Deltares. All rights reserved.                                     
!                                                                               
!-------------------------------------------------------------------------------
!  $Id: tst-shmDatablock-put.F 1180 2012-01-13 17:05:48Z mourits $
!  $HeadURL: https://svn.oss.deltares.nl/repos/delft3d/tags/5.01.00.2163/src/utils_lgpl/delftio/tests/tstShmDataBlocksF77/src/tst-shmDatablock-put.F $
      program test_put_shmds_f77

      integer t, nTimes
      double precision curTime
      character*(100) name

      nTimes = 10
      curTime = 100.D+00
      name = 'testje'

      do t = 1, nTimes
#if (defined(WIN32))
        call sleepqq(999)
#else
        call DIOSYNCcSLEEP(999)
#endif
        curTime = curTime + 10.D+00
        write(*,*) 'Step: ', t, ' Sending: ', curTime
        call dio_shm_f77_putdb_double(name, curTime)
        write(*,*) 'Step: ', t, ' Sent   : ', curTime
      enddo

      call dio_shm_f77_dbcleanup

      end
