 TIMCUR          
 TIMCUR          
 RSAL            
 RTEM            
 DICUV           
 DICWW           
 DISCUM          
 MNKSRC          
 TAUMAX          
 TIMCUR          
 TIMCUR          
 RSAL            
 RTEM            
 DICUV           
 DICWW           
 DISCUM          
 MNKSRC          
 TAUMAX          
 TIMCUR          
 TIMCUR          
 RSAL            
 RTEM            
 DICUV           
 DICWW           
 DISCUM          
 MNKSRC          
 TAUMAX          
No NEFIS errors encountered                                                                                                           
